Use pagination in request
KTH/transfer-to-ladok pull request #21
Opened 2024-02-06 11:55 UTC by me97esn

2024-02-06 11:57 UTC, me97esn commented on packages/t2l-backend/src/externalApis/mongo.ts
> +    .collection<Transference>("transfers_1.2");
This should be discussed: the documents now include a new property: actionIdentifier. Should new documents be created in a now collection, so that documents with differing structure is in another collection? Or how should we handle db schema changes?

2024-02-12 12:45 UTC, exacs requested changes

2024-02-13 15:11 UTC, me97esn commented on packages/t2l-frontend/src/hooks/useSendGrades.ts
> +      const actionIdentifier = `${Math.random()}`;
That's a good question. If the same user clicks twice within some timeframe, do we want to store them separately? I think we should split them into different actions.
If we were to group them together even though they belong to different runs: then this actionIdentifier wouldn't be needed, we already store the userId together with the time created within each document. We either group every document together by _click_, or not at all imo

2024-02-13 15:13 UTC, me97esn commented on packages/t2l-frontend/src/hooks/useSendGrades.ts
> +
That's a good suggestion. Having a function do only one thing is a good design

2024-02-13 15:14 UTC, me97esn commented on packages/t2l-backend/src/apiHandlers/ladokGrades.ts
> +    actionIdentifier: req.body.actionIdentifier,
See comment above https://github.com/KTH/transfer-to-ladok/pull/21#discussion_r1488043261

2024-02-26 14:38 UTC, exacs approved these changes
LGTM!

2024-02-26 14:39 UTC, merged