Link to ladok
KTH/transfer-to-ladok pull request #35
Opened 2024-09-04 12:22 UTC by Epicpants-kth

2024-09-05 09:43 UTC, me97esn commented
I noticed that the link opens up Ladok within the iFrame inside of Canvas (which gives an security error in Firefox). The link should open in a new window/tab, _not_ in the iFrame

2024-09-05 09:44 UTC, me97esn requested changes
I noticed that the link opens up Ladok within the iFrame inside of Canvas (which gives an security error in Firefox). The link should open in a new window/tab, not in the iFrame

2024-09-10 11:32 UTC, exacs requested changes

2024-09-10 11:32 UTC, exacs commented on packages/t2l-backend/src/apiHandlers/utils/types.ts
> +      url: string;
The URL is not sent back to the user, this type should be fixed

2024-09-10 11:32 UTC, exacs commented on packages/t2l-frontend/src/screens/wizard/DoneStep.tsx
> +            Click here to continue the grading in Ladok.
This text is unclear.

- There is no need to say "Click here" (yes, it's a link, I know I should click it)
- It doesn't say what happens when I click it

Better:

```
Continue the grading process in the Report results ("Rapportera") page in Ladok
```

2024-09-10 11:32 UTC, exacs commented on packages/t2l-frontend/src/screens/wizard/PreviewStep.tsx
> -          </a>{" "} */}
Why not include the link anymore? If the link is missing the next paragraph ("From _there_...") is incomplete

2024-09-10 11:44 UTC, me97esn commented on packages/t2l-frontend/src/screens/wizard/PreviewStep.tsx
> -          </a>{" "} */}
This code was removed because it was just commented out code before. It didn't do anything before this PR. I see your point about the "From there" being incomplete, but wasn't that the same before this PR?

2024-09-10 11:45 UTC, me97esn commented on packages/t2l-frontend/src/screens/wizard/DoneStep.tsx
> +            Click here to continue the grading in Ladok.
Good point!

2024-09-10 11:46 UTC, me97esn commented on packages/t2l-backend/src/apiHandlers/utils/types.ts
> +      url: string;
I'm not sure about this, I have to double check. I think I had to add it here, since this type is used elsewhere? Or perhaps that is not the case anymore, I'll check.

2024-09-10 11:49 UTC, me97esn commented on packages/t2l-backend/src/apiHandlers/utils/types.ts
> +      url: string;
This url property is actually needed since we use _backend_ types in the _frontend_. If these lines are removed, then line 19 of DoneStep doesn't compile anymore:
```const url = userSelection?.destination.value.url```

2024-09-10 11:58 UTC, me97esn approved these changes

2024-09-10 14:25 UTC, merged