Show warning when assignment has no letter grades
KTH/transfer-to-ladok pull request #6
Opened 2023-02-23 14:09 UTC by exacs

This PR improves the feedback given to users when the chosen assignment has no letter grades.

1. It allows users to choose any assignment
2. It displays a warning message if an assignment with a type that is not letter grades

2023-03-07 13:30 UTC, me97esn commented on packages/t2l-frontend/src/components/AssignmentSelector.tsx
> +          <option value={a.id}>{a.name}</option>
In version 1 of Transfer to Ladok we sort assignments so that those with letter grade is displayed first. I might be wrong, but it seems that this code doesn't? I think it is a good idea to sort these assignments in the same way. Here is the sorting I'm talking about https://github.com/KTH/lms-export-to-ladok-2/blob/822ebd4986db097d5d243b377c33f8ba2d175411/client/assignment-selector.js#L48

2023-03-07 13:33 UTC, me97esn commented on packages/t2l-frontend/src/components/AssignmentSelector.tsx
> +          <option value={a.id}>{a.name}</option>
In V1 there is an information text about what to do if you can't transfer results because the assignment has a non supported grading type. Is there a reason why this is not included in v2? https://github.com/KTH/lms-export-to-ladok-2/blob/822ebd4986db097d5d243b377c33f8ba2d175411/client/assignment-selector.js#L17

2023-03-07 13:36 UTC, me97esn commented on packages/t2l-frontend/src/screens/Preview.tsx
> +          !assignmentsQuery.data.finalGrades.hasLetterGrade && (
I don't understand this `if` statement. It ends with && <div>...</div>. What does that mean? How does js solve thuthiness of o html tag?

2023-03-07 13:40 UTC, me97esn commented on packages/t2l-backend/src/externalApis/canvasApi.ts
> +    unposted_current_grade: string | null;
Why is this changed within this PR? Is unposted_current_grade being nullable what causes the app to warn if an assignment without letter grade is chosen? Or is there another reason why this is nullable?

2023-03-07 13:41 UTC, me97esn commented on packages/t2l-frontend/src/screens/Preview.tsx
> +                assignment or set letter grade type in course settings.
In V1 there is an information text about what to do if you can't transfer results because the assignment has a non supported grading type. Is there a reason why this is not included in v2? https://github.com/KTH/lms-export-to-ladok-2/blob/822ebd4986db097d5d243b377c33f8ba2d175411/client/assignment-selector.js#L17

2023-03-07 13:52 UTC, exacs commented on packages/t2l-frontend/src/screens/Preview.tsx
> +          !assignmentsQuery.data.finalGrades.hasLetterGrade && (
This is a short-circuit `&&`, which means, do not render anything if any condition is falsy. It is a very common pattern in React

2023-03-07 13:55 UTC, exacs commented on packages/t2l-backend/src/externalApis/canvasApi.ts
> +    unposted_current_grade: string | null;
It turns out that the value **can** be null, which is something we didn't bother before, but now it matters. I've added it to avoid any `undefined is not defined` errors

2023-03-07 13:56 UTC, exacs commented on packages/t2l-frontend/src/screens/Preview.tsx
> +                assignment or set letter grade type in course settings.
The message exist few lines above, L125-L128

2023-03-07 14:08 UTC, exacs commented on packages/t2l-frontend/src/components/AssignmentSelector.tsx
> +          <option value={a.id}>{a.name}</option>
This can be a good idea! I can fix it!

2023-03-14 08:11 UTC, me97esn requested changes
Please fix the sorting of the assignments (as commented) before this PR is merged

2023-03-17 13:06 UTC, merged